[patch.crates-io.autoware_vehicle_msgs]
path = "generated/autoware_vehicle_msgs"

[patch.crates-io.builtin_interfaces]
path = "generated/builtin_interfaces"

[patch.crates-io.geometry_msgs]
path = "generated/geometry_msgs"

[patch.crates-io.nros-core]
path = "../../../nano-ros/packages/core/nros-core"

[patch.crates-io.nros-serdes]
path = "../../../nano-ros/packages/core/nros-serdes"

[patch.crates-io.std_msgs]
path = "generated/std_msgs"
