[patch.crates-io.autoware_adapi_v1_msgs]
path = "generated/autoware_adapi_v1_msgs"

[patch.crates-io.autoware_adapi_version_msgs]
path = "generated/autoware_adapi_version_msgs"

[patch.crates-io.autoware_common_msgs]
path = "generated/autoware_common_msgs"

[patch.crates-io.autoware_control_msgs]
path = "generated/autoware_control_msgs"

[patch.crates-io.autoware_control_validator]
path = "generated/autoware_control_validator"

[patch.crates-io.autoware_internal_debug_msgs]
path = "generated/autoware_internal_debug_msgs"

[patch.crates-io.autoware_internal_metric_msgs]
path = "generated/autoware_internal_metric_msgs"

[patch.crates-io.autoware_internal_msgs]
path = "generated/autoware_internal_msgs"

[patch.crates-io.autoware_internal_perception_msgs]
path = "generated/autoware_internal_perception_msgs"

[patch.crates-io.autoware_internal_planning_msgs]
path = "generated/autoware_internal_planning_msgs"

[patch.crates-io.autoware_operation_mode_transition_manager]
path = "generated/autoware_operation_mode_transition_manager"

[patch.crates-io.autoware_perception_msgs]
path = "generated/autoware_perception_msgs"

[patch.crates-io.autoware_planning_msgs]
path = "generated/autoware_planning_msgs"

[patch.crates-io.autoware_system_msgs]
path = "generated/autoware_system_msgs"

[patch.crates-io.autoware_vehicle_cmd_gate]
path = "generated/autoware_vehicle_cmd_gate"

[patch.crates-io.autoware_vehicle_msgs]
path = "generated/autoware_vehicle_msgs"

[patch.crates-io.builtin_interfaces]
path = "generated/builtin_interfaces"

[patch.crates-io.diagnostic_msgs]
path = "generated/diagnostic_msgs"

[patch.crates-io.geographic_msgs]
path = "generated/geographic_msgs"

[patch.crates-io.geometry_msgs]
path = "generated/geometry_msgs"

[patch.crates-io.logging_demo]
path = "generated/logging_demo"

[patch.crates-io.nav_msgs]
path = "generated/nav_msgs"

[patch.crates-io.nros-core]
path = "../../../nano-ros/packages/core/nros-core"

[patch.crates-io.nros-serdes]
path = "../../../nano-ros/packages/core/nros-serdes"

[patch.crates-io.sensor_msgs]
path = "generated/sensor_msgs"

[patch.crates-io.shape_msgs]
path = "generated/shape_msgs"

[patch.crates-io.std_msgs]
path = "generated/std_msgs"

[patch.crates-io.std_srvs]
path = "generated/std_srvs"

[patch.crates-io.tier4_control_msgs]
path = "generated/tier4_control_msgs"

[patch.crates-io.tier4_external_api_msgs]
path = "generated/tier4_external_api_msgs"

[patch.crates-io.tier4_system_msgs]
path = "generated/tier4_system_msgs"

[patch.crates-io.tier4_vehicle_msgs]
path = "generated/tier4_vehicle_msgs"

[patch.crates-io.unique_identifier_msgs]
path = "generated/unique_identifier_msgs"

[patch.crates-io.visualization_msgs]
path = "generated/visualization_msgs"
