# justfile for autoware_vehicle_cmd_gate

default:
    @just --list

generate:
    cargo nano-ros generate --force

build:
    cargo build

test:
    cargo test

all: generate build

clean:
    rm -rf generated .cargo/config.toml target

clean-bindings:
    rm -rf generated .cargo/config.toml
